version: 1

models:
  - name: dim_hosts_cleansed
    description: Cleansed table which contains Airnbnb hosts. 

  - name: dim_listings_cleansed
    description: Cleansed table which contains Airnbnb listings. 
    columns:

    - name: listing_id
      description: primary key for the listing.
      tests:
        - unique 
        - not_null

    - name: room_type
      description: type of the appartment / room. 
      tests: 
        - accepted_values: 
            values: ['Entire home/apt',
                      'Private room',
                      'Shared room',
                      'Hotel room']    

    - name: host_id
      description: the hosts's id. References the hosts table.
      tests: 
        - not_null
        - relationships: 
            to: ref('dim_hosts_cleansed')
            field: host_id

    - name: minimum_nights 
      description:  '{{ doc("dim_listing_cleansed__minimum_nights") }}'
      tests: 
          - positive_value 
    